# Numpy

In [1]:
# Create numpy array
import numpy as np
array1=np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

In [2]:
# Create numpy array with defined datatype
import numpy as np
array1=np.array([1,2,3,4],np.str) # np.int8, np.int32, np.int64
array1

array(['1', '2', '3', '4'], dtype='<U1')

In [3]:
# Create one dimensional array
import numpy as np
array1=np.array([1,2,3,4])
array1[1]

2

In [4]:
# Create two dimensional array
import numpy as np
array1=np.array([[1,2,3,4],[5,6,7,8]])
print(array1[0])
print(array1[1])
print(array1[1,2])

[1 2 3 4]
[5 6 7 8]
7


In [5]:
# array shape
array1.shape

(2, 4)

In [6]:
# array datatype
array1.dtype

dtype('int32')

In [8]:
# array size
array1.size

8

In [10]:
# array dimension
array1.ndim

2

In [12]:
# size of an element of an array
array1.itemsize

4

In [15]:
# total size of an array
array1.size*array1.itemsize # array1.size*array1.itemsize is equivalent to array1.nbytes

32

In [17]:
# total size of an array
array1.nbytes # array1.size*array1.itemsize is equivalent to array1.nbytes

32

In [19]:
# Access specific element
import numpy as np
array1=np.array([[1,2,3,4],[5,6,7,8]])
array1[1,2]

7

In [21]:
# Get specific row
import numpy as np
array1=np.array([[1,2,3,4],[5,6,7,8]])
array1[1,:]

array([5, 6, 7, 8])

In [23]:
# Get specific column
import numpy as np
array1=np.array([[1,2,3,4],[5,6,7,8]])
array1[:,2]

array([3, 7])

In [24]:
# Get specific row # can use start:end:increment for slicing
import numpy as np
array1=np.array([[1,2,3,4],[5,6,7,8]])
array1[1,1:]

array([6, 7, 8])

In [25]:
# Modify element value
print(array1)
array1[1,2]=12
print(array1)

[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  3  4]
 [ 5  6 12  8]]


In [27]:
# Modify all elements of a row or column
import numpy as np
array1=np.array([[1,2,3,4],[5,6,7,8]])
array1[1,:]=1
print(array1)

[[1 2 3 4]
 [1 1 1 1]]


In [28]:
# Modify all elements of a row or column
import numpy as np
array1=np.array([[1,2,3,4],[5,6,7,8]])
array1[:,2]=2
print(array1)

[[1 2 2 4]
 [5 6 2 8]]


In [26]:
# np.zeros
# create one dimensional array with all elements 0
a1=np.zeros(5)
print(a1)
print(a1.shape)

# create two dimensional array with all elements 0
a2=np.zeros((4,5))
print(a2)
print(a2.shape)

[0. 0. 0. 0. 0.]
(5,)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(4, 5)


In [29]:
# np.ones
# create one dimensional array with all elements 1
a1=np.ones(5)
print(a1)
print(a1.shape)

# create two dimensional array with all elements 1
a2=np.ones((4,5))
print(a2)
print(a2.shape)

[1. 1. 1. 1. 1.]
(5,)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(4, 5)


In [34]:
# np.full(shape,number)
# any other numbers
# create one dimensional array with all elements 10
a1=np.full((1,6),5)
print(a1)
print(a1.shape)

# create two dimensional array with all elements 10
a2=np.full((4,5),5)
print(a2)
print(a2.shape)

[[5 5 5 5 5 5]]
(1, 6)
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
(4, 5)


In [39]:
# np.full_like(array,number)
# any other numbers
# create array like existing array(in terms of shape) with all elements 10
a=np.array([[1,2,3],[4,5,6]])
a1=np.full_like(a,10)
print(a1)

[[10 10 10]
 [10 10 10]]


In [47]:
# Array with random elements np.random.rand(rows,columns)
np.random.rand(4,2)

array([[0.37703389, 0.59014742],
       [0.26820176, 0.45202587],
       [0.68502688, 0.00560597],
       [0.68586525, 0.4835486 ]])

In [59]:
# Random integer values
np.random.randint(96,size=(3,3)) # here 96= max number

array([[51, 66,  3],
       [47, 66,  7],
       [83,  8, 31]])

In [62]:
# Random integer values
np.random.randint(96,1000,size=(3,3)) # here 96,1000 are min and max element number

array([[780, 149, 491],
       [731, 211, 913],
       [945, 804, 676]])

In [46]:
# Array with random elements np.random.random_sample(array.shape)
a=np.array([[1,2,3],[4,5,6]])
np.random.random_sample(a.shape) # Array with random elements and shape same as existing elements 

array([[0.1406243 , 0.68990201, 0.29736503],
       [0.10974738, 0.8738847 , 0.01244206]])

In [32]:
# np.arange
# create one dimensional array with all elements in range 0(inclusive) to 5(exclusive)
a1=np.arange(5)
print(a1)
print(a1.shape)

[0 1 2 3 4]
(5,)


In [36]:
# np.linspace
# create one dimensional array with n elements equally spaced in range of a to b-> np.linspace(a,b,n)
a1=np.linspace(1,5,10)
print(a1)
print(a1.shape)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
(10,)


In [40]:
# np.empty-> Create empty array with random value, these value can be modified afterwards
emp=np.empty(5)
print(emp)


emp2=np.empty((5,3))
print(emp2)

[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [42]:
# np.emptylike-> Create empty array with random value whose shape is like array created earlier, values can be modified afterwards
emp_like=np.empty_like(emp)
print(emp_like)


emp_like2=np.empty_like(emp2)
print(emp_like2)

[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [63]:
# identity matrix of size nXn
ide=np.identity(3)
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
# Repeat an array
arr=np.array([1,2,3,4])
print(np.repeat(arr,4)) # repeat each elements of an array n number of times

arr=np.array([[1,2,3,4],[5,6,7,8]])
print(np.repeat(arr,4)) 

arr=np.array([[1,2,3,4],[5,6,7,8]])
print(np.repeat(arr,4,axis=0)) 

arr=np.array([[1,2,3,4],[5,6,7,8]])
print(np.repeat(arr,4,axis=1)) 

[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4]
[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5 6 6 6 6 7 7 7 7 8 8 8 8]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]
[[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4]
 [5 5 5 5 6 6 6 6 7 7 7 7 8 8 8 8]]


In [12]:
# np.reshape() and np.ravel()
arr=np.arange(99)
arr=arr.reshape(3,33) # reshape array elements should be exact multiple
print(arr)
print(" ")
print(arr.ravel()) # convert array into one dimensional array

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]
 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [13]:
# numpy axis
# In 1D array, -> axis 0
# In 2D array, downwards-> axis=0(column-wise) right-> axis 1(row-wise)

In [23]:
# array.sum()
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(np.sum(arr))
print()
print(np.sum(arr,axis=0))
print()
print(np.sum(arr,axis=1))

36

[ 9 12 15]

[ 3 12 21]


In [25]:
# array.flat: flattens array
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr.flat)
for i in arr.flat:
    print(i)

0
1
2
3
4
5
6
7
8


In [21]:
# np.nbytes
arr.nbytes

36

In [26]:
# array.max(), array.min(), array.mdeian(): maximum element of array
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))

8
0
4.0


In [27]:
# array.max(), array.min(), array.mdeian(): maximum element of array along each axis
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(np.max(arr,axis=0))
print(np.min(arr,axis=0))
print(np.mean(arr,axis=0))
print()
print(np.max(arr,axis=1))
print(np.min(arr,axis=1))
print(np.mean(arr,axis=1))

[6 7 8]
[0 1 2]
[3. 4. 5.]

[2 5 8]
[0 3 6]
[1. 4. 7.]


In [28]:
# array.argmax(), array.min(), array.mdeian(): index of maximum element of array
arr=np.array([[0,1,2],[3,4,5],[6,-7,8]])
print(np.argmax(arr))
print(np.argmin(arr))

8
7


In [29]:
# array.argmax(), array.argmin(), array.argmdeian(): maximum element of array along each aixs
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(np.argmax(arr,axis=0))
print(np.argmin(arr,axis=0))
print()
print(np.argmax(arr,axis=1))
print(np.argmin(arr,axis=1))

[2 2 2]
[0 0 0]

[2 2 2]
[0 0 0]


In [30]:
# argsort()
arr=np.array([0,1,2,93,4,5,6,7,8])
print(arr)
print(np.argsort(arr))

[ 0  1  2 93  4  5  6  7  8]
[0 1 2 4 5 6 7 8 3]


In [31]:
# argsort()
arr=np.array([[0,1,2],[93,4,5],[6,7,8]])
print(arr)
print(np.argsort(arr,axis=0))
print(np.argsort(arr,axis=1))

[[ 0  1  2]
 [93  4  5]
 [ 6  7  8]]
[[0 0 0]
 [2 1 1]
 [1 2 2]]
[[0 1 2]
 [1 2 0]
 [0 1 2]]


# Numpy Mathematics

In [8]:
# Numpy Mathematics
import numpy as np
arr1=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr1+2 # Add 2 to each elements of array
arr1-3 # Subtract 3 from each elements of array
arr1*3 # Multiply 3 to each elements of array
arr1/3 # Divide 3 to each elements of array
arr1//3 # Floor Division
arr1%3 # Modulus
arr1**3 # Power

array([[  0,   1,   8],
       [ 27,  64, 125],
       [216, 343, 512]], dtype=int32)

In [12]:
# sin,cos,tan of all elements of array
import numpy as np
arr1=np.array([[0,1,2],[3,4,5],[6,7,8]])
np.sin(arr1)
np.cos(arr1)
np.tan(arr1)

array([[ 0.        ,  1.55740772, -2.18503986],
       [-0.14254654,  1.15782128, -3.38051501],
       [-0.29100619,  0.87144798, -6.79971146]])

In [43]:
# Array addition
arr1=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr2=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr1)
print(arr2)
print(arr1+arr2) # Element wise addition

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [44]:
# Array multiplication
arr1=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr2=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr1)
print(arr2)
print(arr1*arr2) # Element wise multiplication

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [45]:
# Array transpose
arr1=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr1.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [13]:
# Square root of every elements of array
arr1=np.array([[0,1,2],[3,4,5],[6,7,8]])
np.sqrt(arr1)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [16]:
# Matrix Multiplication
arr1=np.array([[1,1,1],[1,1,1]])
arr2=np.array([[2,2],[2,2],[2,2]])
np.matmul(arr1,arr2)

array([[6, 6],
       [6, 6]])

In [32]:
# Determinent of a matrix
arr1=np.identity(4)
np.linalg.det(arr1)

1.0

# Reorganzing an array

In [37]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=np.reshape(before,(4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Vertical and Horizontal Stacking

In [42]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
np.vstack([arr1,arr2,arr2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [43]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
np.hstack([arr1,arr2,arr1])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])

# Generate numpy array from text file

In [49]:
import numpy as np
file_data=np.genfromtxt("D:\\data.txt",delimiter=",")
file_data.astype('int32')

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

# Boolean Masking and Advanced Indexing

In [54]:
import numpy as np
arr1=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr1>6)
print(arr1[arr1>3])

[[False False False]
 [False False False]
 [False  True  True]]
[4 5 6 7 8]


In [49]:
# np.where(array_condition)
arr1=np.array([[0,1,2],[3,4,5],[6,7,8]])
np.where(arr1>6)

(array([2, 2], dtype=int64), array([1, 2], dtype=int64))

In [52]:
# np.count_nonzero(array): Number of non-zero elements
arr1=np.array([[0,1,2],[3,4,5],[6,7,8]])
np.count_nonzero(arr1)

8

In [54]:
# np.nonzero(array): Tuple of index where non zero elements are found
arr1=np.array([[0,1,2],[3,4,5],[6,0,8]])
np.nonzero(arr1) # 0,0 and 2,1 will not be returned

(array([0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 2], dtype=int64))

In [73]:
####################### Copying an array: Wrong Method
arr=np.array([[1,2,3],[4,5,6]])
arr1=arr # Array cannot be copied in this way
arr1[1,2]=22
print(arr)
print(arr1)

[[ 1  2  3]
 [ 4  5 22]]
[[ 1  2  3]
 [ 4  5 22]]


In [74]:
####################### Copying an array
arr=np.array([[1,2,3],[4,5,6]])
arr1=arr.copy() # Array cannot be copied in this way
arr1[1,2]=22
print(arr)
print(arr1)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5 22]]


# Exercise

In [55]:
# Create array
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1

In [66]:
import numpy as np 
arr_ones=np.ones((5,5))
arr_zeros=np.zeros((3,3))
arr_zeros[1,1]=9
arr_ones[1:4,1:4]=arr_zeros
arr_ones

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])